### ISSUE TITLE
binary traits

### ISSUE THREAD

**Issue by hgw-lcg** [qlu-lab/PUMAS#10]
Hi,
I read in your paper that PUMAS is also applicable to binary traits.
Does this require any special formatting/recoding of my input file  or does it automatically recognize ORs in the BETA column?

Thanks!
Linda

**Comment by zijie02** [comment]
Hi Linda,

Thank you for posting this comment. Yes PUMAS can be applied to binary traits. We haven't provided the script for GWAS QC/reformatting so far. We are working on that and the added script will first clean user input GWAS and then output reformatted summary statistics. Binary GWAS summary statistics obtained from logistic regression will be transformed to observed scale. We'll make it available very soon.

Best,
Zijie

**Comment by qlu-lab** [comment]
Hi Linda,

Apologies for the delayed update. We have uploaded the script and tutorial for cleaning GWAS summary statistics. The script will output summary statistics formatted for PUMAS/PUMACUBS. Please feel free to try it out and let us know if you encounter any issues.

Zijie
