### ISSUE TITLE
SNP weights files

### ISSUE THREAD

**Issue by hgw-lcg** [qlu-lab/PUMAS#11]
Hi,

I have a question regarding the number von SNP weights files needed to evaluate PRS performance.
From the readme I got the impression that only a single file is required (example given was Height.lassosum.txt) but I was wondering how I am supposed to combine the information from all k Iterations in a single file.
Looking into the code of PUMAS.evaluation.R (line 70) I saw that it seems to read in k files called (analogous to the example above) Height.lassosum.ite1.txt to Height.lassosum.itek.txt. 

Does that mean that I need to generate a separate SNP weights file for each Iteration?

Thanks
Linda

**Comment by zijie02** [comment]
Hi Linda,

Yes you'll need k SNP weights files to obtain k-fold MCCV results from PUMAS.

Best,
Zijie
