### ISSUE TITLE
Is FunII.Corr = TRUE fully implemented?

### ISSUE THREAD

**Issue by rkarlssonlinner** [qlu-lab/PUMAS#3]
Hi,

When I change the setting FunII.Corr to TRUE, I get the following error:

> Error in FunI.PEtilde(FunI.XtY.tr = FunII.XtY.train.temp[FunII.r, FunII.order.temp[,  : 
> argument "FunI.Var.Y" is missing, with no default

It appears the argument FunI.Var.Y is missing from the function call on line ~127.

**Comment by qlu-lab** [comment]
Thank you for your feedback!

No, FunII.Corr=T was intended to be implemented and it's not part of the software. It appears that our coder did not delete it from the prototype. We will probably implement it in the future and I'm going to delete this part for now. Sorry for any confusion.

---------
Zijie Zhao

**Comment by rkarlssonlinner** [comment]
Ok. So, therefore, the software should technically only be applied to pruned (but not clumped) summary statistics? Because otherwise there will be many correlated SNPs in the analysis.

**Comment by qlu-lab** [comment]
That's correct. One of the model assumption is exactly independency among predictors.
